apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  labels:
    app: hello-world-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
      - name: hello-world
        image: gcr.io/java-app-315716/hello-world-test:v2.0
        ports:
        - containerPort: 8080
